export const LESSON_BADGES = {
  // 🥉 İlk Adımlar
  FIRST_LESSON_ENTRY: {
    id: 'first_lesson_entry',
    name: 'İlk Adım',
    nameEn: 'First Step',
    description: 'İlk derse giriş yaptın!',
    descriptionEn: 'You entered your first lesson!',
    icon: '🥉',
    color: '#CD7F32',
    rarity: 'common',
    category: 'milestone',
    condition: { type: 'lesson_entry', value: 1, operator: 'gte' },
    reward: { xp: 10, title: 'Öğrenci' },
    unlocksAt: 'lesson_entry',
  },

  // 🥈 İlk Ders Tamamlama
  FIRST_LESSON_COMPLETE: {
    id: 'first_lesson_complete',
    name: 'İlk Dersim',
    nameEn: 'My First Lesson',
    description: 'İlk dersini başarıyla tamamladın!',
    descriptionEn: 'Successfully completed your first lesson!',
    icon: '🥈',
    color: '#C0C0C0',
    rarity: 'uncommon',
    category: 'achievement',
    condition: { type: 'lesson_complete', value: 1, operator: 'gte' },
    reward: { xp: 25, title: 'Başlangıç Ustası' },
    unlocksAt: 'lesson_complete',
  },

  // 🥇 İlk Test Tamamlama
  FIRST_TEST_COMPLETE: {
    id: 'first_test_complete',
    name: 'İlk Testim',
    nameEn: 'My First Test',
    description: 'İlk bölüm testini başarıyla geçtin!',
    descriptionEn: 'Successfully passed your first chapter test!',
    icon: '🥇',
    color: '#FFD700',
    rarity: 'rare',
    category: 'achievement',
    condition: { type: 'test_pass', value: 1, operator: 'gte' },
    reward: { xp: 50, title: 'Test Ustası' },
    unlocksAt: 'test_complete',
  },

  // 💎 Bölüm Ustası Rozetleri
  INTRODUCTION_MASTER: {
    id: 'introduction_master',
    name: 'Giriş Ustası',
    nameEn: 'Introduction Master',
    description: 'Giriş bölümünü mükemmel şekilde tamamladın!',
    descriptionEn: 'Perfectly completed the Introduction chapter!',
    icon: '💎',
    color: '#4F46E5',
    rarity: 'epic',
    category: 'mastery',
    condition: { type: 'chapter_complete', value: 'chapter_0', operator: 'eq' },
    reward: { xp: 100, title: 'Giriş Ustası', unlockFeatures: ['advanced_tips'] },
    unlocksAt: 'chapter_complete',
  },

  BASICS_MASTER: {
    id: 'basics_master',
    name: 'Temel Bilgiler Ustası',
    nameEn: 'Basics Master',
    description: 'Temel bilgiler bölümünü mükemmel şekilde tamamladın!',
    descriptionEn: 'Perfectly completed the Basics chapter!',
    icon: '💎',
    color: '#059669',
    rarity: 'epic',
    category: 'mastery',
    condition: { type: 'chapter_complete', value: 'chapter_1', operator: 'eq' },
    reward: { xp: 150, title: 'Temel Bilgiler Ustası', unlockFeatures: ['code_analyzer'] },
    unlocksAt: 'chapter_complete',
  },

  CONTROL_STRUCTURES_MASTER: {
    id: 'control_structures_master',
    name: 'Kontrol Yapıları Ustası',
    nameEn: 'Control Structures Master',
    description: 'Kontrol yapıları bölümünü mükemmel şekilde tamamladın!',
    descriptionEn: 'Perfectly completed the Control Structures chapter!',
    icon: '💎',
    color: '#DC2626',
    rarity: 'epic',
    category: 'mastery',
    condition: { type: 'chapter_complete', value: 'chapter_2', operator: 'eq' },
    reward: { xp: 200, title: 'Kontrol Yapıları Ustası', unlockFeatures: ['advanced_exercises'] },
    unlocksAt: 'chapter_complete',
  },

  // 👑 Mükemmellik Rozetleri
  PERFECTIONIST: {
    id: 'perfectionist',
    name: 'Mükemmeliyetçi',
    nameEn: 'Perfectionist',
    description: 'Bir testte %100 skor aldın!',
    descriptionEn: 'Scored 100% on a test!',
    icon: '👑',
    color: '#8B5CF6',
    rarity: 'legendary',
    category: 'perfection',
    condition: { type: 'perfect_test', value: 1, operator: 'gte' },
    reward: { xp: 100, title: 'Mükemmeliyetçi', unlockFeatures: ['perfect_badge'] },
    unlocksAt: 'test_perfect',
  },

  SPEED_LEARNER: {
    id: 'speed_learner',
    name: 'Hızlı Öğrenci',
    nameEn: 'Speed Learner',
    description: 'Bir dersi 5 dakikadan kısa sürede tamamladın!',
    descriptionEn: 'Completed a lesson in less than 5 minutes!',
    icon: '⚡',
    color: '#F59E0B',
    rarity: 'rare',
    category: 'speed',
    condition: { type: 'fast_completion', value: 5, operator: 'lte' },
    reward: { xp: 30, title: 'Hızlı Öğrenci' },
    unlocksAt: 'lesson_complete',
  },

  NIGHT_OWL: {
    id: 'night_owl',
    name: 'Gece Kuşu',
    nameEn: 'Night Owl',
    description: 'Gece 22:00\'dan sonra ders tamamladın!',
    descriptionEn: 'Completed a lesson after 22:00!',
    icon: '🦉',
    color: '#6366F1',
    rarity: 'uncommon',
    category: 'special',
    condition: { type: 'time_based', value: 22, operator: 'gte' },
    reward: { xp: 20, title: 'Gece Kuşu' },
    unlocksAt: 'time_based',
  },

  EARLY_BIRD: {
    id: 'early_bird',
    name: 'Erken Kuş',
    nameEn: 'Early Bird',
    description: 'Sabah 06:00\'dan önce ders tamamladın!',
    descriptionEn: 'Completed a lesson before 06:00!',
    icon: '🐦',
    color: '#FBBF24',
    rarity: 'uncommon',
    category: 'special',
    condition: { type: 'time_based', value: 6, operator: 'lte' },
    reward: { xp: 20, title: 'Erken Kuş' },
    unlocksAt: 'time_based',
  },

  // 🔥 Seri Rozetleri
  STREAK_3: {
    id: 'streak_3',
    name: '3 Günlük Seri',
    nameEn: '3-Day Streak',
    description: '3 gün üst üste ders tamamladın!',
    descriptionEn: 'Completed lessons for 3 consecutive days!',
    icon: '🔥',
    color: '#EF4444',
    rarity: 'uncommon',
    category: 'streak',
    condition: { type: 'daily_streak', value: 3, operator: 'gte' },
    reward: { xp: 40, title: 'Kararlı Öğrenci' },
    unlocksAt: 'daily_activity',
  },

  STREAK_7: {
    id: 'streak_7',
    name: '1 Haftalık Seri',
    nameEn: '1-Week Streak',
    description: '7 gün üst üste ders tamamladın!',
    descriptionEn: 'Completed lessons for 7 consecutive days!',
    icon: '🔥',
    color: '#DC2626',
    rarity: 'rare',
    category: 'streak',
    condition: { type: 'daily_streak', value: 7, operator: 'gte' },
    reward: { xp: 100, title: 'Disiplinli Öğrenci' },
    unlocksAt: 'daily_activity',
  },

  // 📚 Bilgi Rozetleri
  KNOWLEDGE_SEEKER: {
    id: 'knowledge_seeker',
    name: 'Bilgi Avcısı',
    nameEn: 'Knowledge Seeker',
    description: '10 ders tamamladın!',
    descriptionEn: 'Completed 10 lessons!',
    icon: '📚',
    color: '#10B981',
    rarity: 'uncommon',
    category: 'progress',
    condition: { type: 'lesson_count', value: 10, operator: 'gte' },
    reward: { xp: 75, title: 'Bilgi Avcısı' },
    unlocksAt: 'lesson_complete',
  },

  SCHOLAR: {
    id: 'scholar',
    name: 'Bilgin',
    nameEn: 'Scholar',
    description: '25 ders tamamladın!',
    descriptionEn: 'Completed 25 lessons!',
    icon: '🎓',
    color: '#7C3AED',
    rarity: 'rare',
    category: 'progress',
    condition: { type: 'lesson_count', value: 25, operator: 'gte' },
    reward: { xp: 150, title: 'Bilgin' },
    unlocksAt: 'lesson_complete',
  },

  MASTER_STUDENT: {
    id: 'master_student',
    name: 'Usta Öğrenci',
    nameEn: 'Master Student',
    description: '50 ders tamamladın!',
    descriptionEn: 'Completed 50 lessons!',
    icon: '👨‍🎓',
    color: '#1F2937',
    rarity: 'epic',
    category: 'progress',
    condition: { type: 'lesson_count', value: 50, operator: 'gte' },
    reward: { xp: 300, title: 'Usta Öğrenci', unlockFeatures: ['master_mode'] },
    unlocksAt: 'lesson_complete',
  },
}; 