import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Quiz, QuizDocument } from '../entities/quiz.entity';

@Injectable()
export class QuizSeeder {
  constructor(
    @InjectModel(Quiz.name) private quizModel: Model<QuizDocument>,
  ) {}

  async seed() {
    const quizzes = [
      // ===== DEĞİŞKENLER KONUSU - 8 QUIZ =====
      
      // Quiz 1: Temel Değişkenler (Kolay)
      {
        id: 'variables_basic_1',
        title: 'Temel Değişkenler - Giriş',
        description: 'C++ değişken türlerinin temellerini öğren',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'easy',
        estimatedTime: 4,
        xpReward: 20,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'C++\'da bir tam sayı değişkeni tanımlamak için hangi anahtar kelime kullanılır?',
            options: ['var', 'let', 'int', 'integer'],
            correctAnswer: 2,
            explanation: 'C++\'da tam sayı değişkenleri tanımlamak için "int" anahtar kelimesi kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Bir ondalıklı sayı değişkeni tanımlamak için ___ anahtar kelimesi kullanılır.',
            correctAnswer: 'float',
            explanation: 'float anahtar kelimesi ondalıklı sayı değişkenleri tanımlamak için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Aşağıdaki kodda eksik olan kısmı tamamlayın:',
            codeTemplate: 'int age = ___;',
            correctAnswer: '25',
            explanation: 'Değişkene uygun bir değer atanmalıdır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 10;\ncout << x;',
            correctAnswer: '10',
            explanation: 'x değişkeni 10 değerine sahip olduğu için ekrana 10 yazdırılır.',
            points: 5,
          },
        ],
      },

      // Quiz 2: Değişken Türleri (Kolay)
      {
        id: 'variables_types_1',
        title: 'Değişken Türleri',
        description: 'Farklı veri türlerini öğren',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'easy',
        estimatedTime: 5,
        xpReward: 25,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'matching',
            question: 'Veri türlerini açıklamalarıyla eşleştirin',
            pairs: [
              { left: 'int', right: 'Tam sayı' },
              { left: 'float', right: 'Ondalıklı sayı' },
              { left: 'char', right: 'Karakter' },
              { left: 'bool', right: 'Mantıksal değer' },
            ],
            correctAnswer: 'matched',
            explanation: 'Bu veri türleri C++\'da temel veri türleridir.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'multiple-choice',
            question: 'Hangi veri türü tek bir karakter saklar?',
            options: ['int', 'char', 'string', 'float'],
            correctAnswer: 1,
            explanation: 'char veri türü tek bir karakter saklamak için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'fill-in-the-blank',
            question: 'Mantıksal değerler için ___ veri türü kullanılır.',
            correctAnswer: 'bool',
            explanation: 'bool veri türü true/false değerleri için kullanılır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'code-completion',
            question: 'Karakter değişkeni tanımlayın:',
            codeTemplate: 'char grade = ___;',
            correctAnswer: 'A',
            explanation: 'Karakter değişkeni tek tırnak içinde tanımlanır.',
            points: 5,
          },
        ],
      },

      // Quiz 3: Değişken Tanımlama (Orta)
      {
        id: 'variables_declaration_1',
        title: 'Değişken Tanımlama',
        description: 'Değişken tanımlama kurallarını öğren',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 6,
        xpReward: 30,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Aşağıdakilerden hangisi geçerli bir değişken adıdır?',
            options: ['2name', '_name', 'my-name', 'class'],
            correctAnswer: 1,
            explanation: 'Değişken adları alt çizgi ile başlayabilir.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Değişken adları ___ ile başlayamaz.',
            correctAnswer: 'rakam',
            explanation: 'Değişken adları rakam ile başlayamaz.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Birden fazla değişkeni aynı anda tanımlayın:',
            codeTemplate: 'int a, b, ___;',
            correctAnswer: 'c',
            explanation: 'Virgül ile ayrılarak birden fazla değişken tanımlanabilir.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 5;\nint y = x;\ncout << y;',
            correctAnswer: '5',
            explanation: 'y değişkeni x\'in değerini alır.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Değişken tanımlama kurallarını eşleştirin',
            pairs: [
              { left: 'Rakam ile başlama', right: 'Geçersiz' },
              { left: 'Alt çizgi ile başlama', right: 'Geçerli' },
              { left: 'Harf ile başlama', right: 'Geçerli' },
              { left: 'Boşluk içerme', right: 'Geçersiz' },
            ],
            correctAnswer: 'matched',
            explanation: 'Değişken adları belirli kurallara uymalıdır.',
            points: 5,
          },
        ],
      },

      // Quiz 4: Değişken Atama (Orta)
      {
        id: 'variables_assignment_1',
        title: 'Değişken Atama',
        description: 'Değişkenlere değer atama işlemleri',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 7,
        xpReward: 35,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Atama operatörü hangisidir?',
            options: ['==', '=', '!=', '>'],
            correctAnswer: 1,
            explanation: '= operatörü atama için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'x değişkenine 10 değerini atayın: x ___ 10;',
            correctAnswer: '=',
            explanation: 'Atama için = operatörü kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Değişkeni tanımlayıp değer atayın:',
            codeTemplate: 'int number ___ 42;',
            correctAnswer: '=',
            explanation: 'Değişken tanımlarken değer atanabilir.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint a = 5;\na = 10;\ncout << a;',
            correctAnswer: '10',
            explanation: 'a değişkeni önce 5, sonra 10 değerini alır.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Atama işlemlerini eşleştirin',
            pairs: [
              { left: 'int x = 5;', right: 'Tanımlama ve atama' },
              { left: 'x = 10;', right: 'Sadece atama' },
              { left: 'int y;', right: 'Sadece tanımlama' },
              { left: 'y = x;', right: 'Değişkenden atama' },
            ],
            correctAnswer: 'matched',
            explanation: 'Farklı atama yöntemleri vardır.',
            points: 5,
          },
        ],
      },

      // Quiz 5: Sabit Değişkenler (Orta)
      {
        id: 'variables_constants_1',
        title: 'Sabit Değişkenler',
        description: 'const anahtar kelimesi ile sabit değişkenler',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 6,
        xpReward: 30,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Sabit değişken tanımlamak için hangi anahtar kelime kullanılır?',
            options: ['static', 'const', 'final', 'constant'],
            correctAnswer: 1,
            explanation: 'const anahtar kelimesi sabit değişkenler için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Sabit bir değişken tanımlayın: ___ int PI = 3.14;',
            correctAnswer: 'const',
            explanation: 'const anahtar kelimesi sabit değişkenler için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Sabit string değişkeni tanımlayın:',
            codeTemplate: 'const string NAME = ___;',
            correctAnswer: '"John"',
            explanation: 'String değerler çift tırnak içinde yazılır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nconst int MAX = 100;\ncout << MAX;',
            correctAnswer: '100',
            explanation: 'Sabit değişken değeri değişmez.',
            points: 5,
          },
        ],
      },

      // Quiz 6: Değişken Kapsamı (Zor)
      {
        id: 'variables_scope_1',
        title: 'Değişken Kapsamı',
        description: 'Değişkenlerin kapsam ve yaşam süresi',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'hard',
        estimatedTime: 8,
        xpReward: 40,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Bir değişken süslü parantez içinde tanımlanırsa nerede geçerlidir?',
            options: ['Tüm programda', 'Sadece o blokta', 'Global olarak', 'Hiçbir yerde'],
            correctAnswer: 1,
            explanation: 'Blok içinde tanımlanan değişkenler sadece o blokta geçerlidir.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Global değişkenler ___ seviyede tanımlanır.',
            correctAnswer: 'fonksiyon',
            explanation: 'Global değişkenler fonksiyon dışında tanımlanır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Global değişken tanımlayın:',
            codeTemplate: 'int globalVar = 10;\nint main() {\n  int localVar = ___;\n}',
            correctAnswer: '5',
            explanation: 'Local değişken main fonksiyonu içinde tanımlanır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 10;\n{\n  int x = 20;\n  cout << x;\n}\ncout << x;',
            correctAnswer: '2010',
            explanation: 'İç bloktaki x, dış bloktaki x\'i gizler.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Değişken kapsamlarını eşleştirin',
            pairs: [
              { left: 'Global değişken', right: 'Tüm programda geçerli' },
              { left: 'Local değişken', right: 'Sadece blokta geçerli' },
              { left: 'Parametre', right: 'Fonksiyon içinde geçerli' },
              { left: 'Static değişken', right: 'Program boyunca kalıcı' },
            ],
            correctAnswer: 'matched',
            explanation: 'Farklı değişken türleri farklı kapsamlara sahiptir.',
            points: 5,
          },
        ],
      },

      // Quiz 7: Değişken Uygulamaları (Zor)
      {
        id: 'variables_applications_1',
        title: 'Değişken Uygulamaları',
        description: 'Gerçek hayat problemlerinde değişken kullanımı',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'hard',
        estimatedTime: 10,
        xpReward: 50,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Öğrenci notu saklamak için hangi veri türü en uygun?',
            options: ['int', 'float', 'char', 'bool'],
            correctAnswer: 1,
            explanation: 'Notlar ondalıklı olabilir, float kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Öğrenci adı için ___ veri türü kullanılır.',
            correctAnswer: 'string',
            explanation: 'İsimler string veri türünde saklanır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Öğrenci bilgilerini tanımlayın:',
            codeTemplate: 'string name = "Ali";\nint age = 20;\nfloat gpa = ___;',
            correctAnswer: '3.75',
            explanation: 'GPA ondalıklı bir değerdir.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nstring name = "Ayşe";\nint age = 18;\ncout << name << " " << age;',
            correctAnswer: 'Ayşe 18',
            explanation: 'String ve int değerler birleştirilir.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Veri türlerini kullanım alanlarıyla eşleştirin',
            pairs: [
              { left: 'int', right: 'Yaş, sayı' },
              { left: 'float', right: 'Not, para' },
              { left: 'string', right: 'İsim, adres' },
              { left: 'bool', right: 'Evet/Hayır' },
            ],
            correctAnswer: 'matched',
            explanation: 'Her veri türü belirli alanlarda kullanılır.',
            points: 5,
          },
        ],
      },

      // Quiz 8: Değişken Master (Çok Zor)
      {
        id: 'variables_master_1',
        title: 'Değişken Master',
        description: 'Değişkenler konusunda uzman seviye',
        skillId: 'variables',
        subjectId: 'basics',
        difficulty: 'hard',
        estimatedTime: 12,
        xpReward: 60,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Aşağıdakilerden hangisi geçersiz bir değişken tanımlamasıdır?',
            options: ['int _var;', 'float 2num;', 'char letter;', 'bool flag;'],
            correctAnswer: 1,
            explanation: 'Değişken adları rakam ile başlayamaz.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Birden fazla değişkeni aynı anda tanımlayıp değer atayın: int a=1, b=2, c=___;',
            correctAnswer: '3',
            explanation: 'Virgül ile ayrılarak birden fazla değişken tanımlanabilir.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Sabit değişkeni tanımlayıp kullanın:',
            codeTemplate: 'const int MAX = 100;\nint value = 50;\nif (value < ___) {',
            correctAnswer: 'MAX',
            explanation: 'Sabit değişken karşılaştırmada kullanılabilir.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 5;\nint y = x++;\ncout << x << " " << y;',
            correctAnswer: '6 5',
            explanation: 'x++ önce değeri döndürür, sonra artırır.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Değişken işlemlerini eşleştirin',
            pairs: [
              { left: 'x++', right: 'Sonra artır' },
              { left: '++x', right: 'Önce artır' },
              { left: 'x--', right: 'Sonra azalt' },
              { left: '--x', right: 'Önce azalt' },
            ],
            correctAnswer: 'matched',
            explanation: 'Artırma/azaltma operatörleri farklı çalışır.',
            points: 5,
          },
        ],
      },

      // ===== OPERATÖRLER KONUSU - 7 QUIZ =====

      // Quiz 9: Temel Operatörler (Kolay)
      {
        id: 'operators_basic_1',
        title: 'Temel Operatörler',
        description: 'Aritmetik operatörlerin temelleri',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'easy',
        estimatedTime: 5,
        xpReward: 25,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'matching',
            question: 'Aritmetik operatörleri işlevleriyle eşleştirin',
            pairs: [
              { left: '+', right: 'Toplama' },
              { left: '-', right: 'Çıkarma' },
              { left: '*', right: 'Çarpma' },
              { left: '/', right: 'Bölme' },
            ],
            correctAnswer: 'matched',
            explanation: 'Bu operatörler temel aritmetik işlemler için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'multiple-choice',
            question: 'Hangi operatör bölme işlemi yapar?',
            options: ['%', '/', '\\', '÷'],
            correctAnswer: 1,
            explanation: '/ operatörü bölme işlemi için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'fill-in-the-blank',
            question: '5 + 3 = ___',
            correctAnswer: '8',
            explanation: 'Toplama işlemi sonucu 8\'dir.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint result = 10 - 3;\ncout << result;',
            correctAnswer: '7',
            explanation: '10 - 3 = 7 sonucunu verir.',
            points: 5,
          },
        ],
      },

      // Quiz 10: Modulo Operatörü (Kolay)
      {
        id: 'operators_modulo_1',
        title: 'Modulo Operatörü',
        description: '% operatörü ile kalan bulma',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'easy',
        estimatedTime: 4,
        xpReward: 20,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Modulo operatörü hangisidir?',
            options: ['/', '%', '\\', 'mod'],
            correctAnswer: 1,
            explanation: '% operatörü modulo (kalan) işlemi için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: '17 % 5 = ___',
            correctAnswer: '2',
            explanation: '17\'yi 5\'e böldüğümüzde kalan 2\'dir.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Çift sayı kontrolü yapın:',
            codeTemplate: 'if (number % 2 == ___) {',
            correctAnswer: '0',
            explanation: 'Çift sayılar 2\'ye bölündüğünde kalan 0 olur.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint remainder = 23 % 7;\ncout << remainder;',
            correctAnswer: '2',
            explanation: '23 % 7 = 2 kalanını verir.',
            points: 5,
          },
        ],
      },

      // Quiz 11: Karşılaştırma Operatörleri (Orta)
      {
        id: 'operators_comparison_1',
        title: 'Karşılaştırma Operatörleri',
        description: 'Büyük, küçük, eşit karşılaştırmaları',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 6,
        xpReward: 30,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Eşitlik kontrolü için hangi operatör kullanılır?',
            options: ['=', '==', '===', 'equals'],
            correctAnswer: 1,
            explanation: '== operatörü eşitlik kontrolü için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Büyük eşit kontrolü için ___ operatörü kullanılır.',
            correctAnswer: '>=',
            explanation: '>= operatörü büyük eşit kontrolü için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'x değişkeninin 10\'dan küçük olduğunu kontrol edin:',
            codeTemplate: 'if (x ___ 10) {',
            correctAnswer: '<',
            explanation: '< operatörü küçük kontrolü için kullanılır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint a = 5;\nint b = 10;\ncout << (a < b);',
            correctAnswer: '1',
            explanation: '5 < 10 true olduğu için 1 yazdırılır.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Karşılaştırma operatörlerini eşleştirin',
            pairs: [
              { left: '==', right: 'Eşit' },
              { left: '!=', right: 'Eşit değil' },
              { left: '>', right: 'Büyük' },
              { left: '<=', right: 'Küçük eşit' },
            ],
            correctAnswer: 'matched',
            explanation: 'Bu operatörler karşılaştırma için kullanılır.',
            points: 5,
          },
        ],
      },

      // Quiz 12: Mantıksal Operatörler (Orta)
      {
        id: 'operators_logical_1',
        title: 'Mantıksal Operatörler',
        description: 'AND, OR, NOT operatörleri',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 7,
        xpReward: 35,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'AND operatörü hangisidir?',
            options: ['&&', '||', '!', '&'],
            correctAnswer: 0,
            explanation: '&& operatörü AND işlemi için kullanılır.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'OR operatörü ___ ile gösterilir.',
            correctAnswer: '||',
            explanation: '|| operatörü OR işlemi için kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'x 10 ile 20 arasında mı kontrol edin:',
            codeTemplate: 'if (x >= 10 ___ x <= 20) {',
            correctAnswer: '&&',
            explanation: 'İki koşul da sağlanmalı, AND kullanılır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nbool a = true;\nbool b = false;\ncout << (a && b);',
            correctAnswer: '0',
            explanation: 'true && false = false (0) sonucunu verir.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Mantıksal operatörleri eşleştirin',
            pairs: [
              { left: '&&', right: 'AND' },
              { left: '||', right: 'OR' },
              { left: '!', right: 'NOT' },
              { left: '!=', right: 'Eşit değil' },
            ],
            correctAnswer: 'matched',
            explanation: 'Bu operatörler mantıksal işlemler için kullanılır.',
            points: 5,
          },
        ],
      },

      // Quiz 13: Artırma/Azaltma Operatörleri (Orta)
      {
        id: 'operators_increment_1',
        title: 'Artırma/Azaltma Operatörleri',
        description: '++ ve -- operatörlerinin kullanımı',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'medium',
        estimatedTime: 6,
        xpReward: 30,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Önce artırma operatörü hangisidir?',
            options: ['x++', '++x', 'x+=1', 'x+1'],
            correctAnswer: 1,
            explanation: '++x önce artırır, sonra değeri döndürür.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'x değişkenini 1 azaltmak için ___ kullanılır.',
            correctAnswer: 'x--',
            explanation: 'x-- operatörü x\'i 1 azaltır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Döngüde sayaç artırın:',
            codeTemplate: 'for (int i = 0; i < 10; i___) {',
            correctAnswer: '++',
            explanation: 'i++ her döngüde i\'yi 1 artırır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 5;\nint y = ++x;\ncout << x << " " << y;',
            correctAnswer: '6 6',
            explanation: '++x önce artırır, sonra değeri döndürür.',
            points: 5,
          },
        ],
      },

      // Quiz 14: Operatör Önceliği (Zor)
      {
        id: 'operators_precedence_1',
        title: 'Operatör Önceliği',
        description: 'Operatörlerin işlem sırası',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'hard',
        estimatedTime: 8,
        xpReward: 40,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: '2 + 3 * 4 işleminin sonucu nedir?',
            options: ['20', '14', '24', '10'],
            correctAnswer: 1,
            explanation: 'Çarpma toplamadan önce yapılır: 2 + (3 * 4) = 14',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'Parantez kullanarak önceliği değiştirin: (2 + 3) * 4 = ___',
            correctAnswer: '20',
            explanation: 'Önce toplama yapılır: (5) * 4 = 20',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Önceliği belirtmek için parantez ekleyin:',
            codeTemplate: 'int result = (a + b) ___ c;',
            correctAnswer: '*',
            explanation: 'Önce toplama, sonra çarpma yapılır.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint result = 10 / 2 + 3;\ncout << result;',
            correctAnswer: '8',
            explanation: 'Önce bölme: 5 + 3 = 8',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Operatör önceliklerini eşleştirin',
            pairs: [
              { left: 'Çarpma/Bölme', right: 'Yüksek öncelik' },
              { left: 'Toplama/Çıkarma', right: 'Orta öncelik' },
              { left: 'Parantez', right: 'En yüksek öncelik' },
              { left: 'Atama', right: 'En düşük öncelik' },
            ],
            correctAnswer: 'matched',
            explanation: 'Operatörlerin belirli öncelik sırası vardır.',
            points: 5,
          },
        ],
      },

      // Quiz 15: Operatör Master (Çok Zor)
      {
        id: 'operators_master_1',
        title: 'Operatör Master',
        description: 'Operatörler konusunda uzman seviye',
        skillId: 'operators',
        subjectId: 'basics',
        difficulty: 'hard',
        estimatedTime: 10,
        xpReward: 50,
        isActive: true,
        questions: [
          {
            id: 'q1',
            type: 'multiple-choice',
            question: 'Aşağıdakilerden hangisi doğru bir ifadedir?',
            options: ['int x = 5 = 3;', 'int x = 5 == 3;', 'int x = 5 && 3;', 'int x = 5 + 3;'],
            correctAnswer: 3,
            explanation: 'Sadece toplama işlemi geçerli bir atama ifadesidir.',
            points: 5,
          },
          {
            id: 'q2',
            type: 'fill-in-the-blank',
            question: 'x değişkeninin 5 ile 15 arasında olduğunu kontrol edin:',
            correctAnswer: 'x >= 5 && x <= 15',
            explanation: 'İki koşul da sağlanmalı, AND kullanılır.',
            points: 5,
          },
          {
            id: 'q3',
            type: 'code-completion',
            question: 'Karmaşık koşul yazın:',
            codeTemplate: 'if ((age >= 18) ___ (hasLicense == true)) {',
            correctAnswer: '&&',
            explanation: 'İki koşul da sağlanmalı.',
            points: 5,
          },
          {
            id: 'q4',
            type: 'output-prediction',
            question: 'Aşağıdaki kodun çıktısı nedir?\nint x = 5;\nint y = 3;\ncout << (x > y ? x : y);',
            correctAnswer: '5',
            explanation: 'Ternary operatör: x > y true olduğu için x döndürülür.',
            points: 5,
          },
          {
            id: 'q5',
            type: 'matching',
            question: 'Operatör türlerini eşleştirin',
            pairs: [
              { left: 'Aritmetik', right: '+, -, *, /' },
              { left: 'Karşılaştırma', right: '==, !=, >, <' },
              { left: 'Mantıksal', right: '&&, ||, !' },
              { left: 'Atama', right: '=, +=, -=' },
            ],
            correctAnswer: 'matched',
            explanation: 'Farklı operatör türleri farklı amaçlara hizmet eder.',
            points: 5,
          },
        ],
      },
    ];

    for (const quiz of quizzes) {
      await this.quizModel.findOneAndUpdate(
        { id: quiz.id },
        quiz,
        { upsert: true, new: true }
      );
    }

    console.log('Quiz seeder completed - 15 quizzes created');
  }
} 